const map = new Map();

map.set('genesis', 'GEN');
map.set('exodus', 'EXO');
map.set('leviticus', 'LEV');
map.set('numbers', 'NUM');
map.set('deuteronomy', 'DEU');
map.set('joshua', 'JOS');
map.set('judges', 'JDG');
map.set('ruth', 'RUT');
map.set('1-samuel', '1SA');
map.set('2-samuel', '2SA');
map.set('1-kings', '1KI');
map.set('2-kings', '2KI');
map.set('1-chronicles', '1CH');
map.set('2-chronicles', '2CH');
map.set('ezra', 'EZR');
map.set('nehemiah', 'NEH');
map.set('esther', 'EST');
map.set('job', 'JOB');
map.set('psalms', 'PSA');
map.set('psalm', 'PSA');
map.set('proverbs', 'PRO');
map.set('ecclesiastes', 'ECC');
map.set('song of solomon', 'SNG');
map.set('song of songs', 'SNG');
map.set('isaiah', 'ISA');
map.set('jeremiah', 'JER');
map.set('lamentations', 'LAM');
map.set('ezekiel', 'EZK');
map.set('daniel', 'DAN');
map.set('hosea', 'HOS');
map.set('joel', 'JOL');
map.set('amos', 'AMO');
map.set('obadiah', 'OBA');
map.set('jonah', 'JON');
map.set('micah', 'MIC');
map.set('nahum', 'NAM');
map.set('habakkuk', 'HAB');
map.set('zephaniah', 'ZEP');
map.set('haggai', 'HAG');
map.set('zechariah', 'ZEC');
map.set('malachi', 'MAL');
map.set('matthew', 'MAT');
map.set('mark', 'MRK');
map.set('luke', 'LUK');
map.set('john', 'JHN');
map.set('acts', 'ACT');
map.set('romans', 'ROM');
map.set('1-corinthians', '1CO');
map.set('2-corinthians', '2CO');
map.set('galatians', 'GAL');
map.set('ephesians', 'EPH');
map.set('philippians', 'PHP');
map.set('colossians', 'COL');
map.set('1-thessalonians', '1TH');
map.set('2-thessalonians', '2TH');
map.set('1-timothy', '1TI');
map.set('2-timothy', '2TI');
map.set('titus', 'TIT');
map.set('philemon', 'PHM');
map.set('hebrews', 'HEB');
map.set('james', 'JAS');
map.set('1-peter', '1PE');
map.set('2-peter', '2PE');
map.set('1-john', '1JN');
map.set('2-john', '2JN');
map.set('3-john', '3JN');
map.set('jude', 'JUD');
map.set('revelations', 'REV');

export { map };

